# Generated by Django 4.2.5 on 2023-09-11 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consutlas',
            new_name='Consulta',
        ),
    ]
