# Generated by Django 4.2.5 on 2023-09-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_alter_consulta_options_consulta_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='lastName',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='gender',
            new_name='sexo',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='aproved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
